name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk unzip zip libffi-dev \
            libssl-dev autoconf libtool pkg-config \
            python3-dev git zlib1g-dev

      - name: Install Cython & Buildozer
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QVR-debug-apk
          path: bin/*.apk
