name: Build APK with Buildozer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk \
            unzip \
            wget \
            git \
            python3-setuptools \
            python3-wheel \
            python3-pip \
            build-essential \
            libssl-dev \
            libffi-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libncurses5-dev \
            libncursesw5-dev \
            zlib1g-dev \
            libsqlite3-dev \
            libjpeg-dev \
            libfreetype6-dev

          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
          unzip tools.zip
          rm tools.zip
          mv cmdline-tools latest   # ← نخلي المسار صح عشان sdkmanager يظهر
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

      - name: Install Required Android SDK Packages
        run: |
          yes | sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-apk
          path: bin/*.apk
